//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANPR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENF_Permits
    {
        public int Id { get; set; }
        public int ENFCustomerId { get; set; }
        public System.DateTime ENFCreatedDateTime { get; set; }
        public string ENFPlateNo { get; set; }
        public string ENFState { get; set; }
        public string ENFSource { get; set; }
        public string ENFType { get; set; }
        public Nullable<System.DateTime> EnfFileDateTime { get; set; }
    }
}
