//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANPR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkVehicle()
        {
            this.PayByCellPlateTxns = new HashSet<PayByCellPlateTxn>();
        }
    
        public int VehicleID { get; set; }
        public string LPNumber { get; set; }
        public string LPLocation { get; set; }
        public string VMake { get; set; }
        public string VModel { get; set; }
        public string VColour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayByCellPlateTxn> PayByCellPlateTxns { get; set; }
    }
}
