//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANPR
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayByCellPlateTxn
    {
        public long PayByCellPlateTxnId { get; set; }
        public int CustomerId { get; set; }
        public string TxnSeqNum { get; set; }
        public string ReceiptId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> ExpiryDateTime { get; set; }
        public System.DateTime TransDateTime { get; set; }
        public Nullable<long> SpaceNum { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> TimePaid { get; set; }
        public Nullable<int> MeterId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string TxnType { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    
        public virtual ParkVehicle ParkVehicle { get; set; }
    }
}
