//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANPR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PemsUsProEntities : DbContext
    {
        public PemsUsProEntities()
            : base("name=PemsUsProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ENF_Permits> ENF_Permits { get; set; }
        public virtual DbSet<EnfVendorTransaction> EnfVendorTransactions { get; set; }
        public virtual DbSet<PayByCellPlateTxn> PayByCellPlateTxns { get; set; }
        public virtual DbSet<ParkVehicle> ParkVehicles { get; set; }
    }
}
